server.port=8080

spring.application.name=clipquery-api

spring.datasource.url=${DB_URL_2}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}

spring.flyway.url=${DB_URL_2}
spring.flyway.user=${DB_USER}
spring.flyway.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=none

jwt.secret=${JWT_SECRET_2}
jwt.expiration=3600000